# Generated by Django 3.0.2 on 2020-01-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current_status_younger',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('elder_1', models.CharField(max_length=20)),
                ('elder_2', models.CharField(max_length=20)),
                ('elder_3', models.CharField(max_length=20)),
                ('elder_4', models.CharField(max_length=20)),
                ('elder_6', models.CharField(max_length=20)),
            ],
        ),
    ]
