# Generated by Django 3.0.2 on 2020-01-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_current_status_younger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_status_younger',
            name='elder_1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='current_status_younger',
            name='elder_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='current_status_younger',
            name='elder_3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='current_status_younger',
            name='elder_4',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='current_status_younger',
            name='elder_6',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
