# Generated by Django 3.0.2 on 2020-01-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_currently_serving_to_elder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currently_serving_to_elder',
            name='stipend',
            field=models.IntegerField(),
        ),
    ]
