# Generated by Django 3.0.2 on 2020-01-05 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200105_0634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='current_status',
        ),
        migrations.DeleteModel(
            name='currently_serving_to_elder',
        ),
    ]
